name: tripforp main ci/cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create application.yml from GitHubSecrets
        run: |
          mkdir -p src/main/resources/
          echo "${{ secrets.APPLICATION_YML }}" | tee src/main/resources/application.yml

      - name: Create .env.development from GitHub Secrets
        run: |
          mkdir -p frontend/
          echo "${{ secrets.ENV_DEVELOPMENT }}" | tee frontend/.env.development

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tripforp-server:${{ github.sha }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tripforp-client:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DOCKER_USERNAME,TAG
          script: |
            set -e
            mkdir -p ~/app 
            cd ~/app
            echo "DOCKER_USERNAME=${DOCKER_USERNAME}" > .env
            echo "TAG=${TAG}" >> .env
            echo "${{ secrets.DOCKER_COMPOSE }}" > docker-compose.yml
            sudo chown -R ubuntu:ubuntu ~/app
            
            echo "docker-compose down 시작(--env-file .env down 제외)"
            docker-compose down
            
            echo "docker-compose pull 시작"
            docker-compose pull
            
            echo "docker-compose up 시작"
            docker-compose up -d
            
            docker image prune -af